// <auto-generated />
using System;
using APIFinantial.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIFinantial.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("APIFinantial.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<double>("Balance")
                        .HasColumnType("double");

                    b.Property<string>("Bank")
                        .HasColumnType("longtext");

                    b.Property<int?>("OwnerAccountUserDataId")
                        .HasColumnType("int");

                    b.Property<int>("UserDateID")
                        .HasColumnType("int");

                    b.HasKey("AccountId");

                    b.HasIndex("OwnerAccountUserDataId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("APIFinantial.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<int>("CategoryType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("APIFinantial.Models.MoneyMovement", b =>
                {
                    b.Property<int>("MoneyMovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MoneyMovementId"));

                    b.Property<int>("AccoountID")
                        .HasColumnType("int");

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.HasKey("MoneyMovementId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryID");

                    b.ToTable("MoneyMovements");

                    b.HasDiscriminator<string>("Discriminator").HasValue("MoneyMovement");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("APIFinantial.Models.UserData", b =>
                {
                    b.Property<int>("UserDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserDataId"));

                    b.HasKey("UserDataId");

                    b.ToTable("UserDatas");
                });

            modelBuilder.Entity("APIFinantial.Models.Expense", b =>
                {
                    b.HasBaseType("APIFinantial.Models.MoneyMovement");

                    b.Property<int>("CategoryType")
                        .HasColumnType("int");

                    b.Property<int>("ExpenseId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Expense");
                });

            modelBuilder.Entity("APIFinantial.Models.Income", b =>
                {
                    b.HasBaseType("APIFinantial.Models.MoneyMovement");

                    b.Property<int>("IncomeId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Income");
                });

            modelBuilder.Entity("APIFinantial.Models.Account", b =>
                {
                    b.HasOne("APIFinantial.Models.UserData", "OwnerAccount")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerAccountUserDataId");

                    b.Navigation("OwnerAccount");
                });

            modelBuilder.Entity("APIFinantial.Models.MoneyMovement", b =>
                {
                    b.HasOne("APIFinantial.Models.Account", "Account")
                        .WithMany("MoneyMovements")
                        .HasForeignKey("AccountId");

                    b.HasOne("APIFinantial.Models.Category", "Category")
                        .WithMany("MoneyMovements")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("APIFinantial.Models.Account", b =>
                {
                    b.Navigation("MoneyMovements");
                });

            modelBuilder.Entity("APIFinantial.Models.Category", b =>
                {
                    b.Navigation("MoneyMovements");
                });

            modelBuilder.Entity("APIFinantial.Models.UserData", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
